# Generated by Django 3.1.2 on 2020-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('media', models.CharField(choices=[('android', 'android'), ('apple', 'apple'), ('behance', 'behance'), ('dribbble', 'dribbble'), ('envelope', 'email'), ('facebook', 'facebook'), ('flickr', 'flickr'), ('foursquare', 'foursquare'), ('google', 'google'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('meetup', 'meetup'), ('pinterest', 'pinterest'), ('reddit', 'reddit'), ('rss', 'RSS'), ('soundcloud', 'soundcloud'), ('snapchat-ghost', 'snapchat'), ('skype', 'skype'), ('spotify', 'spotify'), ('telegram', 'telegram'), ('tumblr', 'tumblr'), ('twitter', 'twitter'), ('vimeo', 'vimeo'), ('whatsapp', 'whatsapp'), ('yahoo', 'yahoo'), ('youtube-play', 'youtube')], max_length=15)),
                ('link', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
                'ordering': ('order',),
            },
        ),
    ]
